name: 'Image Tag Definer'
description: 'Calculate image tag'
outputs:
  latest-tag:
    description: "Docker image tag e.g. 1.0.0"
    value: ${{ steps.calculate-image-tag.outputs.latest-tag }}
  latest-minor-tag:
    description: "Docker image tag e.g. 1.0-latest"
    value: ${{ steps.calculate-image-tag.outputs.latest-minor-tag }}
  latest-major-tag:
    description: "Docker image tag e.g. 1-latest"
    value: ${{ steps.calculate-image-tag.outputs.latest-major-tag }}
runs:
  using: "composite"
  steps:
    - id: calculate-image-tag
      run: ${{ github.action_path }}/calculate-tag.sh
      shell: bash