name: 'Image Tag Definer'
description: 'Calculate image tag'
outputs:
  latest-tag:
    description: "Docker image tag e.g. 1.0.0"
    value: ${{ steps.calculate-image-tag.outputs.latest-tag }}
  latest-minor-tag:
    description: "Docker image tag e.g. 1.0-latest"
    value: ${{ steps.calculate-image-tag.outputs.latest-minor-tag }}
  latest-major-tag:
    description: "Docker image tag e.g. 1-latest"
    value: ${{ steps.calculate-image-tag.outputs.latest-major-tag }}
  is-new-tag:
    description: "true|false"
    value: ${{ steps.calculate-image-tag.outputs.is-new-tag }}
  current-commit:
    description: "Commit hash"
    value: ${{ steps.calculate-image-tag.outputs.current-commit }}
runs:
  using: "composite"
  steps:
    - name: Calculate image tag
      id: calculate-image-tag
      run: ${{ github.action_path }}/calculate-tag.sh
      shell: bash
    - name: Push tags
      run: ${{ github.action_path }}/git-push.sh
      shell: bash
      env:
        BRANCH: ${{ github.ref }}
        TAG: ${{ steps.calculate-image-tag.outputs.latest-tag }}
        IS_NEW_TAG: ${{ steps.calculate-image-tag.outputs.is-new-tag }}
