name: 'Image Tag Definer'
description: 'Calculate image tag'
inputs:
  github-token:
    description: 'Github Access Token. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
outputs:
  latest-tag:
    description: "Docker image tag e.g. 1.0.0"
    value: ${{ steps.calculate-image-tag.outputs.latest-tag }}
  latest-minor-tag:
    description: "Docker image tag e.g. 1.0-latest"
    value: ${{ steps.calculate-image-tag.outputs.latest-minor-tag }}
  latest-major-tag:
    description: "Docker image tag e.g. 1-latest"
    value: ${{ steps.calculate-image-tag.outputs.latest-major-tag }}
  is-new-tag:
    description: "1 or 0"
    value: ${{ steps.calculate-image-tag.outputs.is-new-tag }}
runs:
  using: "composite"
  steps:
    - name: Calculate image tag
      id: calculate-image-tag
      run: ${{ github.action_path }}/calculate-tag.sh
      shell: bash
    - if: ${{ steps.calculate-image-tag.outputs.is-new-tag }} == 1
      name: Push tags
      run: ${{ github.action_path }}/git-push.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.event.inputs.github-token }}
        BRANCH: ${{ github.ref }}
        TAG: ${{ steps.calculate-image-tag.outputs.latest-tag }}